// @bloctop/shared — shared pure logic modules (types, db, logger, permissions, utils)
export * from './types'
export * from './db'
export { getDatabase, clientPromise } from './mongodb'
export { logger, createModuleLogger } from './logger'
export type { LogContext } from './logger'
export { ac, roles, canCreateCrag, canEditCrag, canDeleteCrag, canManagePermissions, canAccessEditor, getEditableCragIds } from './permissions'
export { createRequireAuth } from './require-auth'
export type { AuthInfo, AuthInstance } from './require-auth'
export { API_ERROR_CODES, createErrorResponse } from './api-error-codes'
export type { ApiErrorCode } from './api-error-codes'
export { checkRateLimit, BETA_RATE_LIMIT_CONFIG } from './rate-limit'
export type { RateLimitConfig, RateLimitResult } from './rate-limit'
export { getClientIp, sanitizePathSegment } from './request-utils'
